baseURL = "https://4042302.org"
languageCode = "en-us"
title = "404 â†’ 302"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Aral Balkan"
    description = "A simple gesture for an evergreen Web."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/details/"
    name = "Details"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:hello@ind.ie"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "git"
    weight = 2

[[menu.icon]]
    url = "https://mastodon.ar.al"
    name = "comment"
    weight = 3
